name=NU40DK-KIT
version=0.0.1
author=BARAM
license=MIT
maintainer=BARAM(chcbaram@gmail.com)
sentence=A library for NU40DK-KIT
paragraph=This library supports NU40DK.
category=Communication
url=
architectures=*
depends=